#!/usr/bin/python2.4
#
# Copyright 2007 Google Inc. All Rights Reserved.

"""Text strings for use by Python code.  These are not internationalized.
"""

__author__ = 'kens@google.com (Ken Shirriff)'

ERR_INVALIDFILESPECIFICATION = """The requested file is not available."""
ERR_SAVEPARAMETERS = """An error was encountered while saving collection parameters for %s."""
MSG_ADMIN = """administrator"""
MSG_BAD_TEMPERATURE_SENSOR = """The CPU temperature sensor has failed."""
MSG_DISKADDED = """Disk %s on Machine %s has been added."""
MSG_DISKREMOVED = """Disk %s on Machine %s has been removed."""
MSG_DISK_PROBLEMS = """The disks have problems:"""
MSG_EPOCH_CURRENT_TIME = """Current Time"""
MSG_FORGOTPASSWORD = """Your password is %s
Password requested from %s
 
For security reasons please change your password as soon as possible.
Please contact an administrator if you have any questions.
 """
MSG_FORGOTPASSWORDSUBJECT = """Your password"""
MSG_FULLDISK_MACHINES = """Machines <%s> are almost full."""
MSG_HALFFULLDISK_MACHINES = """Machines <%s> are more than half full."""
MSG_LICENSE_INTERNAL_ERROR = """An internal licensing error has occurred. Cannot perform the current operation. You may be able to solve this problem by installing a new license. Please contact Google to obtain a new license."""
MSG_LICENSE_INVALID = """The current license on the system is invalid. Cannot perform the current operation."""
MSG_LOGNEWUSER = """Created user account: <%s>"""
MSG_LOGSHUTDOWN = """The Google Search Appliance was shut down."""
MSG_LOG_CAPTURE_CRAWLQUEUE = """Capturing current crawl queue %s."""
MSG_LOG_CAPTURE_CRAWLQUEUE_FAILED = """Failed to capture crawl queue %s."""
MSG_LOG_CHANGE_ACCOUNT_TYPE = """Change account type to %s for: <%s>"""
MSG_LOG_CHANGE_EMAIL = """Change email address for: <%s>"""
MSG_LOG_CREATE_COLLECTION = """Created %s: <%s>"""
MSG_LOG_DELETE_COLLECTION = """Deleted %s: <%s>"""
MSG_LOG_DELETE_CRAWLQUEUE = """Delete a captured crawl queue %s."""
MSG_LOG_DELETE_CRAWLQUEUE_FAILED = """Failed to delete a captured crawl queue %s."""
MSG_LOG_DELETE_REPORT = """Delete report %s."""
MSG_LOG_DELETE_REPORT_FAILED = """Failed to delete report %s."""
MSG_LOG_DELETE_USER = """Deleted user account: <%s>"""
MSG_LOG_EXPORT_COLLECTION = """Exported %s: <%s>"""
MSG_LOG_EXPORT_CRAWLQUEUE = """Export a captured crawl queue %s."""
MSG_LOG_EXPORT_CRAWLQUEUE_FAILED = """Failed to export a captured crawl queue %s."""
MSG_LOG_FORCE_USERPASSWORD = """Force new password for user: <%s>"""
MSG_LOG_GENERATE_REPORT = """Generate report %s."""
MSG_LOG_GENERATE_REPORT_FAILED = """Failed to generate report %s."""
MSG_LOG_HALT_MACHINE = """The machine: <%s> was shut down."""
MSG_LOG_IMPORT_COLLECTION = """Imported %s: <%s>"""
MSG_LOG_QUERYEXP_APPLYING = """Applying the query expansion settings."""
MSG_LOG_QUERYEXP_VALIDATION_FAILED = """Query expansion file failed validation.  Entry deleted: %s"""
MSG_LOG_REBOOT_MACHINE = """The machine: <%s> was rebooted"""
MSG_LOG_SET_USERPASSWORD = """Change password for user: <%s"""
MSG_LOG_SSL_CERT_INSTALLED = """SSL certificate installed"""
MSG_LOG_SSL_KEY_INSTALLED = """SSL Key Installed"""
MSG_LOG_UPDATE_REPORT = """Update report %s."""
MSG_LOG_UPDATE_REPORT_FAILED = """Failed to update report %s."""
MSG_MACHINEADDED = """Machine %s has been added to the cluster configuration."""
MSG_MACHINEHALTED = """Machine %s halted."""
MSG_MACHINENEEDSHALT = """Machine %s needs to be halted."""
MSG_MACHINENEEDSREBOOT = """Machine %s needs to be rebooted in order to be used."""
MSG_MACHINEREBOOTED = """Machine %s has been rebooted."""
MSG_MACHINEREMOVED = """Machine %s has been removed from the cluster configuration."""
MSG_MACHINES_CAUTION = """Please monitor the system closely as
the system performance might be affected. If the performance is not
satisfactory, please contact Google technical support for assistance."""
MSG_MACHINES_DOWN = """The following machines have been removed from the cluster configuration: %s."""
MSG_MACHINES_WARNING = """Please contact Google technical support immediately."""
MSG_MACHINE_TOO_HOT_WARNING = """We have detected that the temperature of your system is too high.
Please contact Google support immediately."""
MSG_MACHINE_TOO_WARM_WARNING = """We have detected that the temperature of your system is higher
than normal. You should check to ensure that your machines are properly
ventilated and that the ambient temperature is normal."""
MSG_MAIL_AUTOGENERATED = """This message was generated automatically"""
MSG_MANAGER = """manager"""
MSG_MASTER_LOG_MSG = """[%s logged in from %s at %s]"""
MSG_NEWUSERPASSWORD = """You created a new user account.
 
Username      : %s
Account Type  : %s
Email Address : %s
 
User created from %s by user %s. An email message with 
account information was sent to the user (%s). That 
message includes the following information:
 
  - username
  - password
  - your email address
 
No further action is needed on your side.
 """
MSG_NEWUSERPASSWORDSUBJECT = """A new administrative account has been created for <%s>"""
MSG_PREREQ_FAIL = """The periodic test queries generated the following errors:"""
MSG_PREREQ_FAIL_SUBJECT = """Errors asking test queries"""
MSG_RESET_CRAWL = """Crawl and index reset."""
MSG_SERVING_EPOCH_NOT_CURRENT = """The serving index for collection %s is not the current index."""
MSG_SYSTEM_STATUS_REPORT = """System status report at %s:"""
MSG_UI_LICENSE_EXPIRED = """The license has expired. The software has stopped crawling, indexing, and serving. To re-enable these functions, please contact Google to renew your license."""
MSG_UI_LICENSE_NOTSTARTEDYET = """The existing license file has a start date in the future. You will have to wait until the start date to perform crawling, indexing, and serving."""
MSG_UI_LOG_INDEX_ROLLBACK = """Serving index rolled back to: <%s>"""
MSG_URL_CRAWLED_SINCE_YESTERDAY = """Documents crawled since yesterday:"""
MSG_URL_ERROR_SINCE_YESTERDAY = """Document errors since yesterday:"""
MSG_WELCOMENEWUSER = """Welcome to the Google Search Appliance! 
 
A new %s account was created for you by your administrator, <%s>:
 
Your user name          : %s
Your temporary password : %s
 
This account gives you access to the Web-based Google Admin Console
software. You can log in to the console at %s.
 
To protect the security of your account, please change your password as
soon as possible.
 
Please contact the administrator at %s if you have any questions.
 
Thank you!
 """
MSG_WELCOMENEWUSERSUBJECT = """Welcome!"""
WAR_LICENSE_EMAIL_EXPIRED = """NOTIFICATION: Your Google Search Appliance license has completely expired.
 
This is an automatically generated message.
 
Your Google Search Appliance license has expired and the grace period has ended. The software has stopped crawling, indexing, and serving.
 
To renew your license, please contact Google at appliance-support@google.com."""
WAR_LICENSE_EMAIL_EXPIRING = """NOTIFICATION: You are approaching your Google Search Appliance license expiration date!
 
This is an automatically generated message.
 
Your Google Search Appliance license will expire in %s days. After the license expires, the software will enter a grace period of %s days. After the grace period, the software will stop crawling, indexing, and serving.
 
To extend your license, please contact Google at appliance-support@google.com."""
WAR_LICENSE_EMAIL_IN_GRACE_PERIOD = """NOTIFICATION: Your Google Search Appliance license has expired.
 
This is an automatically generated message.
 
Your Google Search Appliance license has expired. You are now in the grace period. The software will stop crawling, indexing, and serving in %s days.
 
To renew your license, please contact Google at appliance-support@google.com."""
WAR_LICENSE_EMAIL_SUBJECT_EXPIRED = """Your Google Search Appliance license has completely expired."""
WAR_LICENSE_EMAIL_SUBJECT_EXPIRING = """Your license for the Google Search Appliance will expire in %s days."""
WAR_LICENSE_EMAIL_SUBJECT_IN_GRACE_PERIOD = """The grace period of your license for the Google Search Appliance will end in %s days."""
